---
output: md_document
---

```{r message=FALSE, warning=FALSE}
library(MESS)
library(dplyr)
library(survival)
library(quantreg)
source("R/function_model_fit.R") #models
source("R/function_data_analysis.R") #get model results and plots
source("R/Monotone_ROC.R") #get monotoned ROC curve & AUC

```

## Introduction

## read in simulated long and short data
```{r message=FALSE, warning=FALSE}
long.data <- read.csv("Data/reg_data_sim_long.csv")
short.data <- read.csv("Data/reg_data_sim_short.csv")

#set parameters
cutoff.type.basis = "FP"
sens.type.basis = "FP"
covariate1 = c("Z", "Zcont")
covariate2 = c("Z", "Zcont")
tau = 0.8
time.window = 1
nResap = 50

```

## estimate measurement time-varying coefficients

```{r message=FALSE, warning=FALSE}
model.results = analysis_main(long.data, short.data, cutoff.type.basis, sens.type.basis, covariate1, covariate2, tau, time.window, nResap)

#output
model.results$cutoff_plots() 
model.results$sens_plots()

model.results$model_results$model.results$cutoff.model
model.results$model_results$model.results$sensitivity.model

```

## Conditional ROC curve 

```{r message=FALSE, warning=FALSE}
ROC.data = data.frame(vtime = 0.5, Z = 1, Zcont = mean(short.data$Zcont))
tau.set = seq(0.01, 1, 0.05)

ROC.results <- ROC.main(my.newdat = ROC.data, long.data, short.data, tau.set, time.window,
                         cutoff.type.basis = "FP", sens.type.basis = "FP",
                         covariate1 = c("Z", "Zcont"), covariate2 = c("Z", "Zcont"),
                         nResap=50)

#output ROC curve and AUC value
plot_ROC(ROC.results$ROC.results$ROC, my.add = FALSE, my.col = "black", my.lty = 1)
ROC.results$ROC.results$AUC
```

