---
title: "test_packge_code"
output: html_document
date: "2025-04-16"
---


```{r warning=FALSE}

library(joineRML)
library(dplyr)
library(quantreg)
library(ggplot2)
library(readxl)
data0 = read_xlsx("/Users/ana/Library/Mobile Documents/com~apple~CloudDocs/Documents/Specificity_biomarker/sens_spec/HCC_data.xlsx",sheet = 1)
length(unique(data0$ID_No))
data <- data0[!is.na(data0$`AFP (ng/ml)`), ] #remove the obs if AFP is missing

data$id <- sapply(strsplit(data$ID_No, "Deri_Patient"), "[", 2)
#underwent aortic valve replacement using either a stentless valve or a homograft 
colnames(data)[which(colnames(data) == 'AFP (ng/ml)')] <- "AFP"
colnames(data)[which(colnames(data) == 'Cummulated Time since first admission (months)')] <- "visit_time"


long.dat0 <- data.frame(id = as.numeric(data$id), 
                     Xt = log(data$AFP,base = 10),
                     vtime = data$visit_time)



short.dat0 <- data.frame(id = as.numeric(data$id),
                        Y = data$`Overall Survival Time (months)`,
                        delta = data$Death,
                        Z = as.numeric(data$Gender) - 1,
                        gender = as.numeric(data$Gender) -1,
                        age =  as.numeric(data$`Age (years)`),
                        Zcont = as.numeric(data$`Age (years)`/10)) %>%
  filter(data$visit_time == 0) %>%
  mutate(mean.conti = mean(Zcont)) %>%
  mutate(wt_rsap = 1)

length(unique(long.dat0$id))
length(unique(short.dat0$id))

long.dat <- long.dat0[which(long.dat0$id %in% short.dat0$id), ]
short.dat <- short.dat0

length(unique(long.dat$id))
length(unique(short.dat$id))

```


```{r}
library(MESS)
library(splines)
library(dplyr)
library(survival)
library(quantreg)

source("R/fit_sens.R")
source("R/fit_spec.R")
source("R/predict_sens.R")
source("R/predict_spec.R")
source("R/lsurvROC.R")
source("R/process_dat.R")
source("R/function_data_analysis.R") #get model results and plots
source("R/Monotone_ROC.R") #get monotoned ROC curve & AUC
source("R/plot_coef_lsurvROC.R")


model.results = plot_coef_lsurvROC(dat.long = long.dat, 
                                    dat.short = short.dat, 
                                    cutoff.type.basis = "FP", 
                                    sens.type.basis = "FP", 
                                    covariate1 = c("Z", "Zcont"), 
                                    covariate2 = c("Z", "Zcont"), 
                                    tau = seq(0.7, 0.9, 0.05), 
                                    time.window = 12,
                                    nResap = 50,
                                    show_plots = FALSE)

#output
par(mfrow=c(1,3))
model.results$cutoff_plots() 
model.results$sens_plots()
```

